# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-19 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_auto_20211019_1725'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set([('follower', 'followed')]),
        ),
    ]
